      PROGRAM MAIN
C
C	PROGRAMA COM ELEMENTOS LINEARES PARA INTERPOLAÇÃO DO PROBLEMA DE HELMHOTZ
C	VERSÃO COM CALCULO DE NOVA ESTRATÉGIA SEM TERMO REGULARIZADOR MECIC
C     USAM-SE NOVAS FUNÇOES, A SOLUÇÃO FUNDAMENTAL E O TENSOR DE GALERKIN
C     PROBLEMA DE RESPOSTA COM SOLUÇÃO ANALITICA IMPLEMENTADA 
      
	IMPLICIT NONE
	INTEGER NX,NY,NPX,NPY,CC1,CC2,CC3,CC4,I,J
	INTEGER NUM_PON_EXTE_RED,NUM_PON_EXTE_TOT,NUM_PON_INTE,IND
	REAL DX_EXT,DY_EXT,DX_INT,DY_INT
	REAL X_TEMP,Y_TEMP,VARIACAO
	CHARACTER ARQOUT*20,NOME_PROB*128
C	COMMON INT

	write(*,'(A\)')' INFORME NOME DO PROBLEMA-->'
      read(*,'(A20)')NOME_PROB

	write(*,'(A\)')' INFORME A QUANTIDADE DE PONTOS EM X-->'
      read(*,*)NX
	write(*,'(A\)')' INFORME A QUANTIDADE DE PONTOS EM Y-->'
      read(*,*)NY
	write(*,'(A\)')' INFORME A QUANTIDADE DE PONTOS INTERNOS EM X-->'
      read(*,*)NPX
	write(*,'(A\)')' INFORME A QUANTIDADE DE PONTOS INTERNOS EM Y-->'
      read(*,*)NPY
	write(*,'(A\)')' INFORME A CONDICAO DE CONT. EM X = 0 (L.ESQ)>'
      read(*,*)CC1
	write(*,'(A\)')' INFORME A CONDICAO DE CONT. EM Y = 0 (L.SUP)>'
      read(*,*)CC2	
	write(*,'(A\)')' INFORME A CONDICAO DE CONT. EM X = 1 (L.DIR)>'
      read(*,*)CC3
	write(*,'(A\)')' INFORME A CONDICAO DE CONT. EM Y = 1 (L.INF)>'
      read(*,*)CC4

	NUM_PON_EXTE_RED=((NX+NY)*2)-4
	NUM_PON_EXTE_TOT=((NX+NY)*2)
	NUM_PON_INTE=NPX*NPY
	WRITE(*,*) 'NUMERO DE NÓS REDUZIDOS:',NUM_PON_EXTE_RED
	WRITE(*,*) 'NUMERO DE NÓS TOTAIS:   ',NUM_PON_EXTE_TOT
	WRITE(*,*) 'NUMERO DE NÓS INTERNOS :',NUM_PON_INTE


      WRITE(*,'(A\)')' INFORME NOME DO ARQUIVO DE SAIDA --->'
	READ(*,'(A20)')ARQOUT
	  
	!INSERE AS INFORMAÇÕES INICIAIS DO PROBLEMA  
	OPEN(6,FILE=ARQOUT//".TXT")
	WRITE(6,1) NOME_PROB
1	FORMAT(' PROBLEMA CRIADO: ',A)
	WRITE(6,2)NUM_PON_EXTE_RED,NUM_PON_EXTE_TOT,NUM_PON_INTE
2	FORMAT(I3/,I3/,I3)

	!CALCULA A DIFERENÇA ENTRE CADA NÓ
	DX_EXT=1/(NX-1)
	DY_EXT=1/(NY-1)
	DX_INT=1/(NPX+2)
	DY_INT=1/(NPY+2)

	!INICIALIZA OS INDICES
	IND=1
	X_TEMP=0 
	Y_TEMP=0

C	READ(LEC,900) KODE(I),IDUP(I),FI(I)
C900	FORMAT(I5,I6,F12.4)
C	WRITE(IMP,950) I,KODE(I),IDUP(I),FI(I)


100	FORMAT(I3)
101	FORMAT(F5.10)
	DO 3 I=1,NX

		WRITE(6,100)IND
		WRITE(6,101)X_TEMP

		!VARIACAO=I*DX_EXT
		!WRITE(*,*) VARIACAO
		!WRITE(*,*) X_TEMP
		X_TEMP=X_TEMP+DX_EXT
		IND=IND+1
3	CONTINUE
	DO 4 I=1,NY

C		WRITE(6,100)IND,X_TEMP
		Y_TEMP=Y_TEMP+DY_EXT
		IND=IND+1
4	CONTINUE
	DO 5 I=1,NX

C		WRITE(6,100)IND,X_TEMP
		X_TEMP=X_TEMP-DX_EXT
		IND=IND+1
5	CONTINUE
	DO 6 I=1,NY

C		WRITE(6,100)IND,X_TEMP
		Y_TEMP=Y_TEMP-DY_EXT
		IND=IND+1
6	CONTINUE

	X_TEMP=0
	Y_TEMP=0
	
	DO 7 I=1,NPY
	Y_TEMP=Y_TEMP+DY_EXT
	DO 8 J=1,NPX

		X_TEMP=X_TEMP+DX_EXT
C		WRITE(6,100)IND,X_TEMP
		IND=IND+1
8	CONTINUE
	X_TEMP=0
7	CONTINUE













      !write(6,554)J
C554	format(3X,I4)

      !CALL OUTPUT (X,Y,FI,DFI,NX)


      STOP
      END